### ISSUE TITLE
Katex rendering problems

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyter-renderers#117] opened 2018-03-31 11:33 UTC
Firstly, a quick heads-up: [npm](https://www.npmjs.com/package/jupyterlab-katex) still points to https://github.com/jupyterlab/jupyterlab-katex that doesn't exist anymore.

Further, there seems to be some problem with the rendering of fractions specifically: the horizontal bar in the fraction is not visible. To reproduce render `$$\frac{1}{2}$$` in jupyterlab. For me the result looks like this:

![image](https://user-images.githubusercontent.com/2069677/38162772-b3c75bdc-34e7-11e8-9f8c-829166342427.png)

Versions:
```
JupyterLab v0.31.12
Known labextensions:
@jupyterlab/katex-extension
        @jupyterlab/katex-extension v0.14.3  enabled  OK
```
the rendering problem is visible in
Google Chrome 65.0.3325.181 and Mozilla Firefox 59.0.2
on Ubuntu.

**Comment by gnestor** [comment] 2018-04-03 04:15
Thanks for the heads up @akhmerov. 

@ian-r-rose Can you unpublish jupyterlab-katex on npm?

Regarding this issue, I remember there being an issue on jupyterlab or the classic notebook repo regarding a similar issue and I believe the culprit was a Chrome rendering issue that affected some 1px borders. Of course I can't find the issue now, but maybe @ian-r-rose remembers?

**Comment by ian-r-rose** [comment] 2018-04-03 15:48
Thanks @akhmerov, I have deprecated the `jupyterlab-katex` npm package in favor of this one.

The missing fraction bar was due to a bug in Chrome in rounding 1px borders. I was never able to reproduce it myself, but in theory KaTeX v0.9 included a fix for it. We included that version in #59. @akhmerov, can you double check if your build is including v0.9?

**Comment by akhmerov** [comment] 2018-04-03 21:05
Seems to be latest:
```
~/m/e/m/s/j/l/s/node_modules> jlpm list|grep katex                                                                                                                                      (main) 
├─ @jupyterlab/katex-extension@0.14.3
│  └─ katex@^0.9.0
├─ katex@0.9.0
```

**Comment by ian-r-rose** [comment] 2018-04-03 21:06
Hmm, are the fraction bars gone at all zoom levels?

**Comment by akhmerov** [comment] 2018-04-03 21:08
Yep! All the way between 25% and 400%

**Comment by ian-r-rose** [comment] 2018-04-03 21:11
Okay, I can now reproduce the problem. Not sure what's causing it just yet.

**Comment by ian-r-rose** [comment] 2018-04-04 23:53
It looks like the KaTeX rendering saga is not yet over. There is current activity on their repo for how to deal with inconsistent fractions (khan/katex#1173), so they may publish a patch on this. In the meantime, I think I have a temporary fix for this issue. I'll open a PR on it this evening.

**Comment by ian-r-rose** [comment] 2018-04-06 15:43
@akhmerov This should be fixed in the new patch. Thanks @gnestor for the quick release.

**Closed by ian-r-rose** 2018-04-06 15:43 UTC

**Comment by akhmerov** [comment] 2018-04-06 21:06
Great, I can confirm that I observe proper fraction rendering in v0.14.4!

Thanks @ian-r-rose @gnestor
