### ISSUE TITLE
Plotly and Webpack?

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyter-renderers#14] opened 2017-07-26 13:57 UTC
I tried testing out the plotly renderer, but got this error in the browser.

![image](https://user-images.githubusercontent.com/2096628/28624916-54b60064-71e0-11e7-8991-1c56dbca5816.png)

Their readme says that you need a browserify webpack loader to make this work.  @gnestor, have you gotten this renderer to work locally?

https://github.com/plotly/plotly.js#webpack-usage-with-modules

**Comment by gnestor** [comment] 2017-07-26 15:40
Duplicate of https://github.com/jupyterlab/jupyter-renderers/issues/10

**Comment by blink1073** [comment] 2017-07-26 15:46
Oh good

**Comment by gnestor** [comment] 2017-07-26 15:47
This can be easily resolved by importing "plotly.js/lib/core" vs. "plotly.js", this issue however is that `@types/plotly.js` does not explicitly provide type declarations for the "plotly.js/lib/core" module (even though its exports are identical to the defaults exports). I have submitted a PR to DefinitelyTyped to provide this declaration but of course the Travis build is failing: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18392

The goal: use the type declarations from `@types/plotly.js` for "plotly.js/lib/core". If there is a way to do this without changing things on DefibnitelyTyped, that would be great. If not, maybe you can take a look at my PR over there...maybe there is a better way to do this?

**Closed** 2017-08-01 19:32 UTC
