### ISSUE TITLE
plotly scatterplot cutted

### ISSUE THREAD

**Issue by UomoNero2099** [jupyterlab/jupyter-renderers#93] opened 2018-01-31 05:42 UTC
i'm trying to use a plotly scatter or scatter3d. The graph show without a problem but the output cell don't scale with the graph dimension, I attach a shot to show the problem. 

![plotlyscatter3d](https://user-images.githubusercontent.com/35986859/35606918-ecb13e3c-0651-11e8-810b-7914a5f76691.PNG)

This is my configuration: 
```
JupyterLab v0.31.1
Known labextensions:
   app dir: /usr/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.33.0  enabled  OK
@jupyterlab/hub-extension
        @jupyterlab/hub-extension v0.8.0  enabled  OK
@jupyterlab/plotly-extension
        @jupyterlab/plotly-extension v0.14.2  enabled  OK
```

and this is my code for generating the graph

```
data=[]
plotColor=cl.scales['11']['qual']['Set3']
Y = adataMeth.smpm['X_diffmap'][:, :]
for k in range(0,len(ListOfGroup)):
    idxCell = adataMeth.smp['bulk_labels'] == ListOfGroup[k]
    adataMeth[idxCell].smp_names
#     trace=go.Scattergl(
    trace=go.Scatter3d(
        x = Y[idxCell, 0],
        y = Y[idxCell, 1],
        z = Y[idxCell, 2],
        mode = 'markers',
        marker= dict(size= 7,
                    line= dict(width=1),
                    color= plotColor[k],
                    opacity= 0.8
                   ),
        name = ListOfGroup[k],
        text=adataMeth[idxCell].smp_names
    )
    data.append(trace)
                
layout = go.Layout(
#     hoverlabel = bgcolor='#000000',
    autosize=False,
    width=800,
    height=800,
    xaxis=dict(
    showgrid=False,
        zeroline=False,
        showline=False,
        showticklabels=False
    ),
    yaxis=dict(


        showgrid=False,
        zeroline=False,
        showline=False,
        showticklabels=False
    ),
    
    margin=go.Margin(
        l=50,
        r=50,
        b=100,
        t=100,
        pad=4
    )

)
fig = go.Figure(data=data, layout=layout)
iplot(fig)
```

**Comment by gnestor** [comment] 2018-02-22 18:44
This was resolved in https://github.com/jupyterlab/jupyter-renderers/issues/85#issuecomment-365339854. Upgrade to @jupyterlab/plotly-extension 0.14.3: `jupyter labextension install @jupyterlab/plotly-extension`

**Comment by gnestor** [comment] 2018-02-27 22:47
Closing... Feel free to re-open if the issue isn't resolved 👍

**Closed by gnestor** 2018-02-27 22:47 UTC

**Comment by chubukov** [comment] 2019-05-13 13:01
@gnestor I seem to be getting the same error. 

If I render the plot in the last cell, then immediately after rendering it looks fine. But as soon as the new cell gets inserted below, the graph gets cut off.

I'm on windows, with 

```
JupyterLab v0.35.6
Known labextensions:
       @jupyter-widgets/jupyterlab-manager v0.38.1 enabled  ok
        @jupyterlab/plotly-extension v0.18.2 enabled  ok
        jupyterlab-chart-editor v1.1.0 enabled  ok
        plotlywidget v0.10.0 enabled  ok
```

**Comment by gnestor** [comment] 2019-05-15 04:23
I can't reproducce:

```py
import plotly.offline
import numpy as np

data = [dict(
    visible=False,
    line=dict(color='#00CED1', width=6),
    name='v ' + str(step),
    x=np.arange(0,10,0.01),
    y=np.sin(step+np.arange(0,10,0.01))
) for step in np.arange(0,5,0.1)]

data[10]['visible'] = True

fig = dict(data=data)

plotly.offline.iplot(fig)
```

```bash
$ jupyter labextension list
JupyterLab v1.0.0a3
Known labextensions:
   app dir: /Users/grant/anaconda/share/jupyter/lab
        @jupyterlab/plotly-extension v0.18.2  enabled  OK*

   local extensions:
        @jupyterlab/plotly-extension: /Users/grant/Sites/jupyter/jupyter-renderers/packages/plotly-extension
```

```
$ conda list
plotly                    3.6.1                    pypi_0    pypi
```

**Comment by chubukov** [comment] 2019-05-15 17:53
If I change

`fig = dict(data=data)` to

`fig = dict(data=data,layout={'height':800})`

then I reproduce the behavior (next cell cuts off graph). 

![image](https://user-images.githubusercontent.com/13080968/57797565-b9b3ce80-7718-11e9-9780-25567cd012bf.png)


Sorry if this is the expected behavior and the user is meant to be careful with the height.

**Comment by gnestor** [comment] 2019-05-20 23:14
I still can't reproduce (if I scroll down past the edge of my screen, the whole plot is displayed and not cut off):

![image](https://user-images.githubusercontent.com/512354/58057604-4e07a200-7b1a-11e9-8d17-5bdaabd444f3.png)
