### ISSUE TITLE
failing to render after vega3-extension install

### ISSUE THREAD

**Issue by smoh** [jupyterlab/jupyter-renderers#100] opened 2018-02-24 21:30 UTC
I'm failing to render vega-lite charts in jupyterlab after vega3-extension is installed.
```
jupyterlab                0.31.8                   py36_1    conda-forge
---
$ jupyter labextension list
JupyterLab v0.31.8
Known labextensions:
   app dir: /Users/semyeong/anaconda2/envs/research/share/jupyter/lab
@jupyterlab/vega3-extension
        @jupyterlab/vega3-extension v0.14.2  enabled  OK
```

Trying to use [altair](https://github.com/altair-viz/altair), I get
```
JavaScript output is disabled in JupyterLab
```

I also tried copy-paste the example in vega3-extension README, and get empty output.
Can anyone help me getting this to work?

**Comment by domoritz** [comment] 2018-02-24 22:17
Can you check the browser console and update jupyter?

**Comment by smoh** [comment] 2018-02-24 22:26
Yes, so I did the following update:
```
The following packages will be UPDATED:

    jupyter: 1.0.0-py36_3 --> 1.0.0-py36_4

Proceed ([y]/n)? y

jupyter-1.0.0- 100% |######################################################################| Time: 0:00:00   6.09 MB/s
```
In my browser console, I have 
![image](https://user-images.githubusercontent.com/1384435/36635698-a4bcc68e-1987-11e8-936f-7b92699fcc7e.png)

The same code works with just `jupyter notebook` or if I go to `/notebooks/path/to/notebook` and try executing there..

**Comment by domoritz** [comment] 2018-02-24 22:30
This extension only works in jupyter lab. You need https://github.com/vega/ipyvega for Jupyter notebooks.

**Comment by gnestor** [comment] 2018-02-27 22:48
Closing... Feel free to re-open if the issue isn't resolved 👍

**Closed by gnestor** 2018-02-27 22:48 UTC
