### ISSUE TITLE
Heatmaps broken!

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyter-renderers#22] opened 2017-08-31 06:42 UTC
On jupyterlab 0.27.0 with the latest jupyter-renderers installed when plotting a heatmap it instead plots a line graph!

What I'm seeing on jupyterlab:
![image](https://user-images.githubusercontent.com/881019/29909896-3454d6ea-8e6b-11e7-9f96-af54b951a056.png)

What I see locally in nteract:
![image](https://user-images.githubusercontent.com/881019/29909915-443cdcc4-8e6b-11e7-939f-a1bbc361357d.png)

**Comment by dhirschfeld** [comment] 2017-08-31 06:43
Test code:
```python
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot

init_notebook_mode()

trace = go.Heatmap(z=[[1, 20, 30, 50, 1], [20, 1, 60, 80, 30], [30, 60, 1, -10, 20]],
                   x=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                   y=['Morning', 'Afternoon', 'Evening'])
data=[trace]
iplot(data)
```

**Comment by dhirschfeld** [comment] 2017-09-02 01:16
Just to confirm, Using the same notebook served by the same jupyterhub instance when viewed in jupyterlab (at `/lab` url) the heatmap renders as a line plot but when viewed in the notebook (at `/tree` url) the heatmap renders correctly!

**Comment by gnestor** [comment] 2017-09-16 01:58
Duplicate of https://github.com/jupyterlab/jupyter-renderers/issues/21

**Closed by gnestor** 2017-09-16 01:58 UTC

**Comment by gnestor** [comment] 2017-09-26 18:19
I just published [@jupyterlab/plotly-extension](https://www.npmjs.com/package/@jupyterlab/plotly-extension) 0.10.0 which should resolve this issue 👍
