### ISSUE TITLE
Can not Sankey Diagram in Plotly

### ISSUE THREAD

**Issue by ktong** [jupyterlab/jupyter-renderers#41] opened 2017-10-03 22:18 UTC
Tried to render Sankey diagram in plotly using [demo code](https://plot.ly/python/sankey-diagram/). However, it's blank in Jupyterlab even it works well in classical notebook.

**Comment by ktong** [comment] 2017-10-03 22:23
## JupyterLab
![newplot](https://user-images.githubusercontent.com/4332577/31151943-aaaf5f8e-a84e-11e7-8b14-d4edc803fd56.png)

## Classical Notebook
![newplot 1](https://user-images.githubusercontent.com/4332577/31151944-aaaf497c-a84e-11e7-81bd-c9a589b76c96.png)

**Comment by dhirschfeld** [comment] 2017-10-03 22:46
Seems to work for me (modulo being squished up because of #38):
![image](https://user-images.githubusercontent.com/881019/31152625-5106b2ba-a8e0-11e7-984e-a2f3d5f15cb6.png)

Are you sure you've got the latest version of the JupyterLab plotly extension installed?

**Comment by dhirschfeld** [comment] 2017-10-03 22:56
The latest version is `0.10.0` published recently.

I'm not sure how well just installing over the top of an existing extension works so to be super cautious I uninstall first:
```
jupyter labextension uninstall @jupyterlab/plotly-extension
jupyter lab clean
jupyter labextension install @jupyterlab/plotly-extension
jupyter lab build
```
Not sure if the last build is required - again, just being super cautious.

**Comment by ktong** [comment] 2017-10-03 23:24
It works with 0.10.0. However, it seems missing color for nodes

**Comment by dhirschfeld** [comment] 2017-10-03 23:44
> *However, it seems missing color for nodes*

I see that too. Not sure what the issue is there.

**Comment by gnestor** [comment] 2017-10-05 23:01
I tested this as well and the colors do show up after resizing the window or panel (the more narrow, the more it shows up 🤔). 

Note: `plotly.offline.init_notebook_mode` does not work with jupyterlab but you can use `plotly.offline.iplot` without it. 

I'm going to close this issue but feel free to open another one for the sankey charts not displaying colors until they're resized.

**Closed by gnestor** 2017-10-05 23:01 UTC
