### ISSUE TITLE
Installation of katex-extension is trying to clone a non-existent Github repo

### ISSUE THREAD

**Issue by mgeier** [jupyterlab/jupyter-renderers#98] opened 2018-02-23 11:20 UTC
I'm getting this:

```sh
$ jupyter labextension install @jupyterlab/katex-extension
> /usr/bin/npm pack @jupyterlab/katex-extension
...
npm ERR! git clone git@github.com:jupyterlab/katex-extension ERROR: Repository not found.
...
```

I don't know it that's relevant, but I'm using a development install of JupyterLab.

**Comment by gnestor** [comment] 2018-02-27 22:47
I just published a new version of the katex-extension. It's possible that the current version on npm 4 days ago was the version that existed at https://github.com/jupyterlab/katex-extension (which was then moved here).

**Comment by gnestor** [comment] 2018-02-27 22:48
Closing... Feel free to re-open if the issue isn't resolved 👍

**Closed by gnestor** 2018-02-27 22:48 UTC

**Comment by mgeier** [comment] 2018-03-02 16:14
Thanks for the update, but it probably didn't have anything to do with my error ...

I just found out that I'm running a hopelessly old version of `npm` on my (up-to-date!) Debian/testing system (it looks like they don't have a current `npm` package anymore?):

```
$ npm --version
1.4.21
```

I tried this:

```
npm install -g npm
```

... which installed a newer version to `/usr/local/bin/npm`:

```
$ npm --version
5.7.1
```

Now it works nicely!

It doesn't work on my development install of JupyterLab, though.
Is there anything special I have to do for that?

**Comment by mgeier** [comment] 2018-03-03 10:01
I've seen `jlpm`, but why are you recommending `yarn` in https://github.com/jupyterlab/jupyter-renderers/blob/master/packages/katex-extension/README.md?

I didn't actually run `npm`, it was somehow automatically called by `jupyter labextension install`.

**Comment by gnestor** [comment] 2018-03-05 18:17
Those are developer instructions in https://github.com/jupyterlab/jupyter-renderers/blob/master/packages/katex-extension/README.md (e.g. people who want to install katex-extension locally and develop against it). To build katex-extension is different than building jupyterlab. When you run `jupyter lab build`, it will re-build jupyterlab along with all installed/linked extensions.

I'm pretty sure that `jupyter labextension install` uses `jlpm` exclusively vs `npm`...

@mgeier Is everything working for you now?

**Comment by blink1073** [comment] 2018-03-05 18:23
We use `npm` for `npm pack`, since `yarn pack` has different semantics.

**Comment by ian-r-rose** [comment] 2018-03-05 18:27
@mgeier, it looks like some of the README.md docs are out of date in recommending yarn. Thanks for flagging that!

**Comment by mgeier** [comment] 2018-03-11 19:31
> Is everything working for you now?

The normal installation worked nicely, the development installation didn't.
But I gave up on it when I saw that KaTeX doesn't support the `align` environment yet, which is a showstopper for me.

**Comment by ian-r-rose** [comment] 2018-03-12 03:24
@mgeier For what it's worth, KaTeX works with `aligned`. It makes the assumption that all the markup is already in math mode (which is the case for `aligned`, but not `align`).

**Comment by mgeier** [comment] 2018-03-12 11:24
Thanks, @ian-r-rose, I know, but that's not good enough for me.
I'll just wait until KaTeX has it (I guess it's https://github.com/Khan/KaTeX/issues/604), and then I'll check if MathJaX is still that much slower, and then I'll decide again.
